version: "3.8"

services:
  mongodb:
    restart: always
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    container_name: ${CONTAINER_NAME}

  mongo-express:
    image: mongo-express
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${DATABASE_URL}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb

  bot:
    restart: always
    depends_on:
      - mongodb
    build: .
    volumes:
      - ./:/app
      - ./bot/storage/logs:/app/storage/logs